version: '3'
services:
  web-with-redis:
    build: ./simple_redis_server_ping
    ports:
    - "1323:1323"
    links:
    - redis
  web:
    build: ./simple_server
    ports:
    - "1323:1323"
  redis:
    build: ./redis-server
